In [1]:
%matplotlib inline
import pandas as pd
import numpy as np
import matplotlib
# matplotlib.use('agg')
import matplotlib.pyplot as plt
import os
# from tqdm.notebook import  tqdm
from tqdm import  tqdm
import talib
import datetime
import math
import  mplfinance as mpf

import sys
sys.path.append('../../DataSource/baostock')
import datasource
sys.path.append('../..')
import Utils
# 这个是筛选多少天上涨多少的，
codes = datasource.get_codes()
print(f'股票数量:{len(codes)},第一支股票:{codes[0]}')
code = codes[0]
dt = datasource.getData(code)
dt.head()

股票数量:5521,第一支股票:sh.600000

,code,open,high,low,close,preclose,volume,amount,adjustflag,turn,tradestatus,pctChg,peTTM,pbMRQ,psTTM,pcfNcfTTM,isST
date,,,,,,,,,,,,,,,,,
2010-01-04,sh.600000,64.829140,64.947929,62.839423,62.928515,64.413379,66191338,1.419984e+09,1,0.835129,1,-2.3052,14.435065,2.877081,5.316299,7.091240,0
2010-01-05,sh.600000,63.581855,64.086709,61.740624,63.403671,62.928515,115147943,2.436891e+09,1,1.452808,1,0.7551,14.287342,2.898805,5.178308,7.144784,0
2010-01-06,sh.600000,63.225488,63.255185,62.007900,62.156386,63.403671,96782575,2.034174e+09,1,1.221095,1,-1.9672,14.006279,2.841779,5.076439,7.004231,0
2010-01-07,sh.600000,62.007900,62.483056,60.285458,60.760614,62.156386,85236072,1.761801e+09,1,1.075414,1,-2.2456,13.691757,2.777965,4.962444,6.846945,0
2010-01-08,sh.600000,60.404247,61.770322,60.285458,61.443652,60.760614,65707646,1.349532e+09,1,0.829026,1,1.1241,13.845672,2.809193,5.018229,6.923915,0

In [3]:
# 全部股票查看
dts = []
for i in tqdm(range(len(codes))):
    code = codes[i]
    dt = datasource.getData(code)
    dt['preClose']=dt['close'].shift()
    dt['upRate'] = abs(dt['close']-dt['preClose'])/dt['preClose']*100
    dt2 = dt.loc[dt['upRate']>10.5,:]
    if len(dt2) > 0:
        dts.append(dt2)
dt_all = pd.concat(dts)
print(len(dt_all))
dt_all.head()

100%|█████████████████████████████████████████████████████████████████████████████| 5521/5521 [00:50<00:00, 108.77it/s]

75

,code,open,high,low,close,preclose,volume,amount,adjustflag,turn,tradestatus,pctChg,peTTM,pbMRQ,psTTM,pcfNcfTTM,isST,preClose,upRate
date,,,,,,,,,,,,,,,,,,,
2011-08-29,sh.600057,34.452363,37.584396,31.529132,33.157789,16.620655,75719729.0,621577228.0,1,31.016493,1,99.4975,-78.832346,8290.018918,NaN,-200.786342,0,16.620655,99.497487
2020-07-23,sh.600069,1.512069,1.512069,1.512069,1.512069,1.695350,195800.0,64614.0,1,0.012100,1,-10.8108,-0.814588,0.407799,0.318499,-2.070106,0,1.695350,10.810811
2020-07-28,sh.600069,1.099686,1.099686,1.099686,1.099686,1.237147,223200.0,53568.0,1,0.013700,1,-11.1111,-0.592428,0.296581,0.231636,-1.505532,0,1.237147,11.111111
2020-04-20,sh.600074,3.834719,3.834719,3.834719,3.834719,4.294885,190500.0,95250.0,1,0.018600,1,-10.7143,-1.307637,-0.203870,7.568934,-394.382726,0,4.294885,10.714286
2020-04-24,sh.600074,2.530914,2.530914,2.530914,2.530914,2.837692,736900.0,243177.0,1,0.071800,1,-10.8108,-0.863040,-0.134554,4.995496,-260.292599,0,2.837692,10.810811