这个是看数据中有多少个数据超过10%涨停

In [1]:
%matplotlib inline
import pandas as pd
import numpy as np
import matplotlib
# matplotlib.use('agg')
import matplotlib.pyplot as plt
import os
# from tqdm.notebook import  tqdm
from tqdm import  tqdm
import talib
import datetime
import math
import  mplfinance as mpf

import sys
sys.path.append('../../DataSource/同花顺')
import datasource
sys.path.append('../..')
import Utils
# 这个是筛选多少天上涨多少的，
codes = datasource.get_codes()
print(f'股票数量:{len(codes)},第一支股票:{codes[0]}')
code = codes[0]
dt = datasource.getData(code)
dt.head()

股票数量:6974,第一支股票:000001

   Id    Code       Date   Open   High    Low  Close       Amount      Volume
0   1  000001 2014-01-02  12.12  12.30  12.05  12.23  596223740.0  48991089.0
1   2  000001 2014-01-03  12.15  12.16  11.78  11.93  656631300.0  55111484.0
2   3  000001 2014-01-06  11.89  12.00  11.50  11.67  679280380.0  58211823.0
3   4  000001 2014-01-07  11.53  11.76  11.51  11.63  393977580.0  33840749.0
4   5  000001 2014-01-08  11.64  11.95  11.53  11.76  538436170.0  45776816.0

In [2]:
dt['preClose']=dt['Close'].shift()
dt['upRate'] = (dt['Close']-dt['preClose'])/dt['preClose']*100

In [3]:
dt2 = dt.loc[dt['upRate']>10.5,:]
dt2.head()

Empty DataFrame
Columns: [Id, Code, Date, Open, High, Low, Close, Amount, Volume, preClose, upRate]
Index: []

In [6]:
# 全部股票查看
dts = []
for i in tqdm(range(len(codes))):
    code = codes[i]
    dt = datasource.getData(code)
    dt['preClose']=dt['Close'].shift()
    dt['upRate'] = abs(dt['Close']-dt['preClose'])/dt['preClose']*100
    dt2 = dt.loc[dt['upRate']>10.5,:]
    if len(dt2) > 0:
        dts.append(dt2)
dt_all = pd.concat(dts)
dt_all.head()

100%|██████████████████████████████████████████████████████████████████████████████| 6974/6974 [01:25<00:00, 81.39it/s]

,Id,Code,Date,Open,High,Low,Close,Amount,Volume,preClose,upRate
106,107,000001,2014-06-12,9.62,9.77,9.60,9.71,3.559050e+08,36744198.0,11.78,17.572156
308,309,000001,2015-04-13,17.00,17.16,16.15,16.54,8.021097e+09,480715320.0,19.80,16.464646
597,598,000001,2016-06-16,8.57,8.60,8.53,8.57,3.311924e+08,38667008.0,10.44,17.911877
1463,1464,000001,2020-05-22,13.33,13.34,12.92,12.92,1.119433e+09,85623733.0,16.45,21.458967
1329,4083,000002,2020-05-22,25.51,25.54,25.14,25.16,1.351550e+09,53424167.0,32.18,21.814792

In [7]:
len(dt_all)

50374

看起来这个同花顺的本地数据是很有问题的。